name = "Hackercraft"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8995a23c77cb9c50cf663ad81c9073cc12742bc84ddbc925b89d22b85a3af785"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
