name = "Hackercraft"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f813c3bebb480935e1531eca1d8ca1bdc2ede7fec7072f393d6c725f0287cafd"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
